name: ClansFork
author: cofob
version: 0.0.1
main: ru.cofob.Clans.Main
api-version: 1.13
description: Simple Clans plugin
database: false

commands:
  clan:
    description: Manage your Clan

softdepend: [PlaceholderAPI]
